name: Experiment Build and Run CI 

on:
  push:
    branches:
      - main
      - parallel
  pull_request:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build_and_run:
    runs-on: ubuntu-22.04 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up C++ Build Environment 
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential # Устанавливает g++ и make

    - name: Build Project 
      run: make

    - name: Run Project 
      run: ./labwork
